### ISSUE TITLE
Primo VE and addons

### ISSUE THREAD

**Issue by uleodolter** [ShoulM/Primo-App-Store#7]
It seems there is an issue with Primo VE and addons. 

I tried the following Primo VE and Altmetrics addon.
https://uah.primo.exlibrisgroup.com/discovery/search?vid=01UAH_INST:01UAH_V1&lang=en&sortby=rank

The resulting js/custom.js starts with following lines

```javascript
(function(){
"use strict";
'use strict';

//Auto generated code by primo app store DO NOT DELETE!!! -START-
/*
    hookName is a place holder with should hold the hook name not including "prm" at the beginning and in upper camel case
    e.g: for hook prmSearchBarAfter (in html prm-search-bar-after) it should be given "SearchBarAfter"
 */
app.controller('FullViewAfterController', [function () {
    var vm = this;
}]);
```

As you can see `app` is not defined,  it seems that `custom.module.js` is missing when using Primo VE.  This is different to non Primo VE, where i can see readonly `js/custom.module.js` in editor which creates the `app` variable. 

Please check

**Comment by gilax** [comment]
@uleodolter. can you please check that your issue is really fixed?

**Comment by uleodolter** [comment]
@gilax yes it works now, thx
